include:
  - docker-compose-base.yml
services:
  rs3:
    image: public.ecr.aws/j8q9y0n6/responsiveinc/rs3:0.1.0-main.24.0
    platform: linux/amd64
    container_name: rs3
    hostname: rs3
    ports:
      - 50051:50051
    environment:
      CONFIG_FILE: /etc/rs3/rs3.toml
    volumes:
      - ./volumes/rs3.toml:/etc/rs3/rs3.toml
    networks:
      backend:
        ipv4_address: 10.0.0.50
