from scratch
COPY config/docker-compose.yml /docker-compose.yml
COPY config/volumes/scylla.yaml volumes/scylla.yaml
COPY config/volumes/app.properties /volumes/app.properties
COPY config/volumes/log4j2.properties /volumes/log4j2.properties
ADD config/volumes/zookeeper /volumes/zookeeper
ADD config/volumes/scylla /volumes/scylla
ADD config/volumes/scylla2 /volumes/scylla2
ADD config/volumes/kafka /volumes/kafka
