name: "AWS, ECR & Docker Hub Login"
description: "Configure credentials and log in to AWS ECR & Docker Hub"

inputs:
  role-to-assume:
    default: arn:aws:iam::292505934682:role/github-responsive-pub-main
    required: false
    description: "the role to assume"
  role-session-name:
    required: true
    description: "the name of the session"
  aws-region:
    required: true
    description: "the region (generally us-west-2, or us-east-1 for public repo)"
  public:
    default: "false"
    required: false
    description: "whether to set registry-type: public (true/false)"

# Note: only one of the below outputs will be non-empty, depending on the value of inputs.public
outputs:
  registry:
    description: "the private ECR registry that was logged into"
    value: ${{ steps.login-ecr.outputs.registry }}
  public-registry:
    description: "the public ECR registry that was logged into"
    value: ${{ steps.login-ecr-public.outputs.registry }}

runs:
  using: composite
  steps:
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: "Login to Amazon ECR"
      if: ${{ inputs.public == 'false' }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: "Login to public Amazon ECR"
      if: ${{ inputs.public == 'true' }}
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: "Login to Docker Hub"
      uses: docker/login-action@v3
      with:
        username: responsivedev
        password: ${{ secrets.DOCKERHUB_TOKEN }}