##
# Executes a given action on all modules with a specified group, where a
# "module group" is defined as a set of modules with direct dependencies
# on each other. Module groups are defined by a single, shared version.
#
# Module groups may contain 1 or more modules, and are named after the
# "root" module in the dependency tree (if one exists). Practically
# speaking, they should be named after the module where the version of
# the entire group is originally defined.
#
# The current groups with more than one module are defined below
#
# root: kafka-client
#  - responsive-test-utils
#
#
# TODO: figure out if we can pass action names directly as input so we
#       don't have to hard-code the mapping like we do now.
#       Something like this does not seem to work:
#
#       uses: ./.github/actions/${{ inputs.action }}
#
#       We may be able to use a strategy matrix to more cleanly define
#       the module groups if/when this becomes overly complex or error
#       prone
#
##
name: "For Module in Group"
description: "Executes the provided action on all modules in the group"
inputs:
  module:
    required: true
    description: "the module (or module group) to act on"
  action:
    required: true
    description: "the action to execute (options: gradle-build-and-publish)"
  OSSRH_USER:
    required: false
    description: "the OSSRH user for publishing actions (found in the 'secrets' context)"
  OSSRH_PASSWORD:
    required: false
    description: "the OSSRH password for publishing actions (found in the 'secrets' context)"
  SIGNING_KEY:
    required: false
    description: "the signing key for publishing actions (found in the 'secrets' context)"
  SIGNING_PASSWORD:
    required: false
    description: "the signing key password for publishing actions (found in the 'secrets' context)"
runs:
  using: composite
  steps:
    - name: "Gradle Build & Publish | Root Module"
      if: ${{ inputs.action == 'gradle-build-and-publish' }}
      uses: ./.github/actions/gradle-build-and-publish
      with:
        module: ${{ inputs.module }}
        OSSRH_USER: ${{ inputs.OSSRH_USER }}
        OSSRH_PASSWORD: ${{ inputs.OSSRH_PASSWORD }}
        SIGNING_KEY: ${{ inputs.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ inputs.SIGNING_PASSWORD }}

    - name: "Gradle Build & Publish | kafka-client: responsive-test-utils"
      if: ${{ (inputs.module == 'kafka-client') && (inputs.action == 'gradle-build-and-publish') }}
      uses: ./.github/actions/gradle-build-and-publish
      with:
        module: "responsive-test-utils"
        skip_release: "true"
        OSSRH_USER: ${{ inputs.OSSRH_USER }}
        OSSRH_PASSWORD: ${{ inputs.OSSRH_PASSWORD }}
        SIGNING_KEY: ${{ inputs.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ inputs.SIGNING_PASSWORD }}
