[server]
listen_port = 50051

[metastore]
metastore_type = "Static"

[[metastore.static_store.stores]]
id = "b1a45157-e2f0-4698-be0e-5bf3a9b8e9d1"
name = "e2e"

[metastore.static_store.stores.options]
logical_shards = 8
store_type = "Basic"

[storage.slatedb]
wal_enabled = false

[storage.slatedb.block_cache]
mode = "Default"

[cloud_provider]
provider = "Aws"

[cloud_provider.aws]
region = ""
bucket = "rs3-antithesis"
s3_endpoint = "http://minio:9000"
s3_retry_timeout_millis = 1800000
