[server]
listen_port = 50051

[store_provider]
provider = "Static"

[store_provider.static_store.slatedb]
wal_enabled = false

[store_provider.static_store.slatedb.block_cache]
mode = "Default"

[[store_provider.static_store.stores]]
id = "b1a45157-e2f0-4698-be0e-5bf3a9b8e9d1"
pss = [{ id = 0 }, { id = 1 }, { id = 2 }, { id = 3 }, { id = 4 }, { id = 5 }, { id = 6 }, { id = 7 }]

[cloud_provider]
provider = "Aws"

[cloud_provider.aws]
region = ""
bucket = "rs3-antithesis"
s3_endpoint = "http://minio:9000"
s3_retry_timeout_millis = 1800000
