name: Antithesis Manual Run
on:
  workflow_dispatch:
    inputs:
      backend:
        description: 'The backend storage type to use'
        type: choice
        required: true
        default: 'scylla'
        options:
          - scylla
          - mongo
      test-duration:
        description: 'The duration that the antithesis test runs'
        type: string
        required: false
        default: '0.5'
jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write # This is required for actions/checkout (read) and publishing tags (write)
    uses: ./.github/workflows/github-e2e.yaml
    with:
      backend: ${{ inputs.backend }}
      test-duration: ${{ inputs.test-duration }}
    secrets: inherit
