name: Build
on:
  pull_request:
    branches:
      - main
      - 'patch/**'

jobs:

  # ===================     CLEAN       ===================

  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

  # ===================     BUILD       ===================

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: "Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2.9.0

      - name: "Build"
        run: ./gradlew build buildDocker -x test

      - name: "Save Docker Images"
        run: docker image save -o /tmp/responsive-images.tar responsivedev/responsive-operator responsivedev/simple-example

      - name: "Cache Docker Images"
        uses: actions/upload-artifact@v3
        with:
          name: responsive-images
          path: /tmp/responsive-images.tar

  # ===================     TEST        ===================

  test:
    if: false
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    needs: [build]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: "Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2.9.0

      - name: "test"
        run: ./gradlew test

  # ===================     TEST        ===================

  smoke-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    needs: [ build ]
    steps:
      - name: "Download Cached Images"
        uses: actions/download-artifact@v3
        with:
          name: responsive-images
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/responsive-images.tar
          docker image ls -a