name: Antithesis Test Run 
on: workflow_dispatch
jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write # This is required for actions/checkout (read) and publishing tags (write)
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true

      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: refs/heads/e2e-test
          submodules: recursive
          fetch-depth: 0

      - name: "Gradle Build"
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: kafka-client-examples:e2e-test:build kafka-client-examples:e2e-test:buildDocker

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: _json_key
          password: ${{ secrets.ANTITHESIS_DOCKER_CREDENTIAL }}

      - name: "Tag Docker"
        run: |
          docker tag e2e-test:`./gradlew kafka-client:cV  | grep "Project version" | sed 's/Project version: //'` us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test:antithesis-latest

      - name: "Push Docker"
        run: |
          docker push us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test:antithesis-latest

      - name: "Build Config"
        working-directory: ./kafka-client-examples/e2e-test/docker/antithesis
        run: |
          docker build . -t us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test-config:antithesis-latest

      - name: "Push Config"
        run: |
          docker push us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test-config:antithesis-latest
