name: Build
on:
  pull_request:
    branches:
      - main
      - 'patch/**'

jobs:

  # ===================     CLEAN       ===================

  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

  # ===================   JAVA TESTS    ===================
  # NOTE: I considered caching the result of the docker build and uploading
  # the artifacts so that we wouldn't need to rebuild them again for the
  # smoke test, but this proved to take just as long as building it from scratch
  # (without running tests) and doesn't take up space in the GHA cache

  java-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: "Build"
        uses: ./.github/actions/build

      - name: "test"
        run: ./gradlew test

  # ===================     SMOKE TEST  ===================

  smoke-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: "Build"
        uses: ./.github/actions/build

      - name: "Build Docker Images"
        run: ./gradlew buildDocker -x test

      - name: "Checkout sindri"
        uses: actions/checkout@v3
        with:
          repository: responsivedev/sindri
          path: sindri
          ref: refs/heads/main
          token: ${{ secrets.TOOLS_GHA_TOKEN }}

      - name: "Install Kind"
        uses: helm/kind-action@v1.5.0
        with:
          install_only: true

      - name: "Run Smoke Test"
        run: |
          sindri/scripts/update-versions -u -s responsiveOperator -e local -i responsive-operator:`./gradlew operator:cV | grep Project.version | sed 's/Project version: //'`
          sindri/scripts/update-client-versions -s main -p false -i simple-example -t `./gradlew kafka-client:cV  | grep "Project version" | sed 's/Project version: //'`
          sindri/scripts/run-smoke-test -l -w system-tests-pub-pr-${PR_NUMBER} -s main
        env:
          PR_NUMBER: ${{ github.event.number }}
          DD_SERVICE: "https://us5.datadoghq.com/"
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}