name: Antithesis Test Run
on:
  workflow_call:
    inputs:
      backend:
        description: 'The backend storage type to use'
        type: string
        required: true
        default: 'mongo'
      test-type:
        description: 'Which test variant to run'
        type: string
        required: true
        default: 'regression'
      test-duration:
        description: 'The duration that the antithesis test runs'
        type: string
        required: false
        default: '0.5'
jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write # This is required for actions/checkout (read) and publishing tags (write)
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: https://us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ANTITHESIS_DOCKER_CREDENTIAL }}

      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOOLS_GHA_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: "Gradle Build kafka-client"
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: kafka-client:build -xtest

      - name: "Gradle Build"
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: kafka-client-examples:e2e-test:build kafka-client-examples:e2e-test:buildDocker

      - name: "Set Kafka Client Version"
        run: |
          echo "KAFKA_CLIENT_VERSION=$(./gradlew kafka-client:cV  | grep "Project version" | sed 's/Project version: //')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: kafka_client_version

      - name: "Tag Docker"
        env:
          KAFKA_CLIENT_VERSION: ${{ steps.kafka_client_version.outputs.KAFKA_CLIENT_VERSION }}
        run: |
          docker tag e2e-test:$KAFKA_CLIENT_VERSION us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test:$KAFKA_CLIENT_VERSION

      - name: "Push Docker"
        env:
          KAFKA_CLIENT_VERSION: ${{ steps.kafka_client_version.outputs.KAFKA_CLIENT_VERSION }}
        run: |
          docker push us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test:$KAFKA_CLIENT_VERSION

      - name: "Build Test Config"
        working-directory: ./kafka-client-examples/e2e-test/docker/antithesis
        env:
          KAFKA_CLIENT_VERSION: latest
          BACKEND: ${{ inputs.backend }}
          CONFIG_IMG_VERSION: ${{ steps.kafka_client_version.outputs.KAFKA_CLIENT_VERSION }}
        run: |
          cat ${{ inputs.test-type }}/config/docker-compose.yml.template | envsubst > ${{ inputs.test-type }}/config/docker-compose.yml
          cp ${{ inputs.test-type }}/config/volumes/app-$BACKEND.properties ${{ inputs.test-type }}/config/volumes/app.properties
          docker build . -f ${{ inputs.test-type }}/Dockerfile -t us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test-config-${{ inputs.test-type }}:$CONFIG_IMG_VERSION

      - name: "Push Config"
        env:
          KAFKA_CLIENT_VERSION: ${{ steps.kafka_client_version.outputs.KAFKA_CLIENT_VERSION }}
        run: |
          docker push us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test-config-${{ inputs.test-type }}:$KAFKA_CLIENT_VERSION

      - name: "Run Antithesis Tests"
        uses: antithesishq/antithesis-trigger-action@main
        with:
          notebook_name: responsive
          tenant: responsive
          username: ${{ secrets.ANTITHESIS_USERNAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.ANTITHESIS_GH_PAT }}
          config_image: us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test-config-${{ inputs.test-type }}:${{ steps.kafka_client_version.outputs.KAFKA_CLIENT_VERSION }}
          images: us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test:${{ steps.kafka_client_version.outputs.KAFKA_CLIENT_VERSION }};docker.io/mongo:5.0;public.ecr.aws/j8q9y0n6/responsiveinc/rs3-antithesis:0.1.0-main.64.0.patch-object-store-retries.2;docker.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
          description: "responsive antithesis test run"
          email_recipients: "antithesis-responsive-aaaamurlsqy6e3hxnx6ksnec5y@antithesisgroup.slack.com"
          additional_parameters: |-
            custom.duration=${{ inputs.test-duration }}
            custom.database_type=${{ inputs.backend }}
            custom.test_type=${{ inputs.test-type }}

      #  env:
      #    KAFKA_CLIENT_VERSION: ${{ steps.kafka_client_version.outputs.KAFKA_CLIENT_VERSION }}
      #    ANTITHESIS_USERNAME: ${{ secrets.ANTITHESIS_USERNAME }}
      #    ANTITHESIS_PASSWORD: ${{ secrets.ANTITHESIS_PASSWORD }}
      #    DURATION: 0.5
      #    TEST_TYPE: async
      #  run: |
      #    curl -u "$ANTITHESIS_USERNAME:$ANTITHESIS_PASSWORD" -XPOST https://responsive.antithesis.com/api/v1/launch_experiment/responsive -d '{"params": {"antithesis.images":"us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test:'$KAFKA_CLIENT_VERSION'", "antithesis.config_image": "us-central1-docker.pkg.dev/molten-verve-216720/responsive-repository/e2e-test-config-async:'$KAFKA_CLIENT_VERSION'", "custom.duration": '$DURATION', "antithesis.report.recipients": "antithesis-responsive-aaaamurlsqy6e3hxnx6ksnec5y@antithesisgroup.slack.com", "
