apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole 
metadata:
  name: {{ printf "%s-app-role" (include "responsive-operator.fullname" .)  }}
  labels:
    {{- include "responsive-operator.role.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
