apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "responsive-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "responsive-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsiveoperator
  strategy:
     type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: responsiveoperator
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "responsive-operator.serviceAccountName" . }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['bash', '/init-operator']
          env:
              - name: LOGGING_KAFKA_EP
                value: {{ .Values.logging.kafka.endpoint }}
              - name: LOGGING_TOPIC
                value: {{ .Values.logging.kafka.topic }}
              - name: LOGGING_KAFKA_KEY_FILE
                value: /mnt/secretcfg/logging_kafka_key.properties
          volumeMounts:
            - name: cfg
              mountPath: /etc/responsive-operator/
              readOnly: true
            - name: secretcfg
              mountPath: /mnt/secretcfg
            {{- if ne .Values.logging.kafka.keySecret "" }}
            - name: logging-kafka-key
              mountPath: /etc/responsive-operator/logging_kafka/
              readOnly: true
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
              - name: CONTROLLER_EP
                value: {{ .Values.controllerEndpoint }}
              - name: LOGGING_KAFKA_EP
                value: {{ .Values.logging.kafka.endpoint }}
              - name: LOGGING_TOPIC
                value: {{ .Values.logging.kafka.topic }}
              - name: OPERATOR_OPTS
                value: {{ .Values.operatorOpts }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: secretcfg
              mountPath: /mnt/secretcfg
              readOnly: true
      volumes:
        - name: cfg
          secret:
            secretName: {{ .Values.controllerSecret }}
            optional: true
            defaultMode: 0444
        - name: secretcfg
          emptyDir:
            sizeLimit: 4Mi
        {{- if ne .Values.logging.kafka.keySecret "" }}
        - name: logging-kafka-key
          secret:
            secretName: {{ .Values.logging.kafka.keySecret }}
            optional: true
            defaultMode: 0444
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
