apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-responsive-rolebinding" (include "responsive-operator.fullname" .)  }}
  labels:
    {{- include "responsive-operator.role.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-responsive-role" (include "responsive-operator.fullname" .)  }}
subjects:
- kind: ServiceAccount
  name: {{ include "responsive-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
